### PR TITLE
2020-05 updates

### PR DESCRIPTION
**Pull request by mjpieters**
This brings mbdata up to par with MB Server again.

- Fix Python-2-ism in gentools.py
- Run the SQL and model generation steps
- Update the fresh install instructions (new script to run)
- Add notes on upgrading to PostgreSQL 12.

### CODE REVIEW

**Comment by sfussenegger** [comment]
Thanks for your effort!

> The `updates/20200518-pg12-after-upgrade.sql` script probably needs some custom re-writing.
> 
> I had to run the extensions alterations by hand as a superuser, and alter the role name in two other statements.

Could you please elaborate on this?

**Comment by mjpieters** [comment]
> I had to run the extensions alterations by hand as a superuser, and alter the role name in two other statements.

The before- and after-upgrade scripts appear to have two purposes:

- Dropping indexes and functions that are no longer used for anything
- Replace indexes and custom functions to move to native PG functionality rather than using custom extensions. This includes [adding a dependency on the `unaccent` extension](https://github.com/lalinsky/mbdata/blob/a40567ee6b2879199da42cf0225ad462628d8953/mbdata/sql/updates/20200518-pg12-after-upgrade.sql#L14-L15)
- Correcting for past errors as to where extensions are registered (specifically [the `cube` extension](https://github.com/lalinsky/mbdata/blob/a40567ee6b2879199da42cf0225ad462628d8953/mbdata/sql/updates/20200518-pg12-after-upgrade.sql#L8-L12), for which a [new bridge function in the musicbrainz schema is created](https://github.com/lalinsky/mbdata/blob/a40567ee6b2879199da42cf0225ad462628d8953/mbdata/sql/updates/20200518-pg12-after-upgrade.sql#L17-L22)).

The commands altering or creating extensions need superuser access, so can't be run directly with `mbslave`. In addition, there are [two lines that assign ownership](https://github.com/lalinsky/mbdata/blob/a40567ee6b2879199da42cf0225ad462628d8953/mbdata/sql/updates/20200518-pg12-after-upgrade.sql#L64-L65) for two functions, and these hardcode the owner role. In our setup we use a different role name so I had to alter those statements accordingly.

**Comment by heyoni** [comment]
Hey @lalinsky , any reason for delaying this pull request? I'm thinking of using this branch before my upgrade :)

**Comment by heyoni** [comment]
Thanks @lalinsky

**Pull request merged**
